//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManufacturer
    {
        public int ManufacturerID { get; set; }
        public string Manufacturer_Name { get; set; }
    }
}
